# https://aka.ms/yaml

trigger:
  branches:
    include: 
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job: build_image
        dependsOn: build_content
        displayName: Build Image
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: 'Yashica'
              repository: 'azdevops/openweather2nats'
              command: 'buildAndPush'
              buildContext: $(Pipeline.Workspace)
              tags: |
                $(Build.BuildId)
                latest
